# server
server:
  port: 8080

# spring
spring:
  application:
    name: ma-api

  # spring database
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ma3?autoReconnect=true
    username: ade
    password:

  # spring JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        format_sql: true

  # spring flyway
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    table: flyway_schema_version

  # spring mail
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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

# logging
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

# mail
mail:
  from: postmaster@sandbox8ef10d5c5b5f462baeef1d00943fa340.mailgun.org
  fromName: Metal Archives
  to: alan.dellonze@gmail.com

# ma discography
ma:
  metal-archives:
    url: https://www.metal-archives.com/band/discography/id/%s/tab/all
  path:
    main: /Users/ade/Downloads/- MISC/music/
    tmp: "- tmp/"
    cover: covers/
    mp3: mp3/
    scans: scans/
