# server
server:
  port: 8080

# spring
spring:
  application:
    name: ma-api

  # spring database
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/ma3?autoReconnect=true
    username: ade
    password:

  # spring JPA properties
  jpa:
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: false
        format_sql: true

  # spring flyway
  flyway:
    enabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
    table: flyway_schema_version

  # spring mail
  mail:
    host: smtp.mailgun.org
    port: 587
    username: postmaster@sandbox8ef10d5c5b5f462baeef1d00943fa340.mailgun.org
    password: eea9efd51d6a37a8cf34a55051cca2db-09001d55-515ff747

# logging
logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR

# mail
mail:
  from: postmaster@sandbox8ef10d5c5b5f462baeef1d00943fa340.mailgun.org
  fromName: Metal Archives
  to: alan.dellonze@gmail.com

# ma discography
ma.url: https://www.metal-archives.com/band/discography/id/%s/tab/all
