# server
server:
  port: 8080
  compression.enabled: true
  tomcat.threads.max: 50
  error.include-message: always

# spring
spring:
  # application
  application:
    version: "@project.version@"
    name: "@project.name@"
    description: "@project.description@"

  # datasource
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/ma3?currentSchema=public"
    username: "ade"
    password:
    hikari:
      minimum-idle: 1 # default: 10
      maximum-pool-size: 2 # default: 10
      idle-timeout: 120000 # default: 600000

  # jpa
  jpa:
    open-in-view: false
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: false

  # mail
  mail:
    host: "smtp.sendgrid.net"
    port: 587
    username: "apikey"
    password: "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"

# ma
ma:
  # metal-archives website
  metal-archives:
    url: "https://www.metal-archives.com/band/discography/id/%s/tab/all"

  # path (for mp3, covers, etc...)
  path:
    main: "/Users/ade/Downloads/- MISC/music/"
    tmp: "- tmp/"
    covers: "covers/"
    mp3: "mp3/"
    scans: "scans/"

  # mail
  mail:
    from: "postmaster@sandbox8ef10d5c5b5f462baeef1d00943fa340.mailgun.org"
    fromName: "Metal Archives"
    to: "alan.dellonze@gmail.com"
